config/routes.rb
TigerLaundry::Application.routes.draw do

  devise_for :users

  resources :facilities do
    resources :submissions do
      collection do
        get 'limited'
      end
    end
  end

  resources :users


  # Map the root of the site to the pages controller
  root to: "pages#index"
  get 'about', to: "pages#about"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :ldap_authenticatable, :rememberable, authentication_keys: [:username]

  has_many :submissions

  before_save do
    Rails.logger.debug "############"
    Rails.logger.debug username
    entry = Devise::LDAP::Adapter.get_ldap_entry(username)
    Rails.logger.debug "!!!!!!!!!!!!!!!!!!!!!!!"
    self.name  = entry[:cn][0]
    self.email = username + "@rit.edu"
  end

  def admin?
    privilege_level >= 100
  end

  def mod?
    privilege_level >= 50
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_mod, only: [:new, :edit, :create, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :privilege_level)
    end

    def require_mod
      if not current_user or not current_user.mod?
        redirect_to users_path
      end
    end
end

app/views/users/_form.html.haml
= form_for @user, html: {class: "form-horizontal"} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: "control-label col-md-2"
    .col-md-10
      = f.text_field :name, class: "form-control", placeholder: "Name"
  .form-group
    = f.label :email, class: "control-label col-md-2"
    .col-md-10
      = f.text_field :email, class: "form-control", placeholder: "Email"
  .form-group
    = f.label :privilege_level, class: "control-label col-md-2"
    .col-md-10
      = f.text_field :privilege_level, class: "form-control", placeholder: "Privilege Level"
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit 'Save', class: "btn btn-primary"

app/views/users/edit.html.haml
%h1
  Editing
  = @user.name

= render 'form'

.btn-group
  = link_to 'Show', @user, class: "btn btn-default"
  = link_to 'Show All', users_path, class: "btn btn-default"

app/views/users/index.html.haml
%h1.text-center All Users

.row
  .col-md-12
    - @users.each do |user|
      .panel.panel-default
        .panel-heading
          = render 'shared/username', user: user
        .panel-body
          .row
            .col-md-12
              %b Submissions
              = user.submissions.count

app/views/users/show.html.haml
%h1.text-center= @user.name

.btn-group
  = link_to 'Edit', edit_user_path(@user), class: "btn btn-default"

%h2 Submissions
.table-responsive
  %table.table
    %tr
      %th Facility
      %th Time
      %th Washers
      %th Driers
    - @user.submissions.each do |submission|
      %tr
        %td= link_to submission.facility.name, facility_path(submission.facility)
        %td= submission.created_at
        %td= submission.washers
        %td= submission.driers