config/routes.rb
TigerLaundry::Application.routes.draw do

  devise_for :users

  resources :facilities do
    resources :submissions do
      collection do
        get 'limited'
      end
    end
  end

  resources :users


  # Map the root of the site to the pages controller
  root to: "pages#index"
  get 'about', to: "pages#about"
  
end

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for type}"}
    %button.close{:"data-dismiss" => "alert"} x
    = message

app/views/shared/_nav.html.haml
.navbar.navbar-default.navbar-inverse.navbar-static-top{role:"navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{:type =>"button",
                            :"data-toggle"=>"collapse",
                            :"data-target"=>".navbar-ex1-collapse"}
        %span.sr-only "Toggle navigation"
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "TigerLaundry", root_url, {class:"navbar-brand"}
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav
        -# active class is only applied to the current controller's link
        %li{class: ("active" if params[:controller] == 'facilities')}
          = link_to "Facilities", facilities_url
        %li{class: ("active" if params[:controller] == 'users')}
          = link_to "Users", users_url
        %li{class: ("active" if params[:controller] == 'pages' && params[:action] == 'about')}
          = link_to "About", about_url
      - if user_signed_in?
        %ul.nav.navbar-nav.pull-right.navbar-collapse-hidden
          %li= link_to current_user.name, user_path(current_user)
          %li
            %a{href: destroy_user_session_path}
              Logout
              .glyphicon.glyphicon-log-out
        %ul.nav.navbar-nav.navbar-collapse-only
          %li= link_to current_user.name, user_path(current_user)
          %li
            %a{href: destroy_user_session_path}
              Logout
              .glyphicon.glyphicon-log-out
      - else
        -# IF THE NAVBAR IS COLLAPSED
        %ul.nav.navbar-nav.pull-right.navbar-collapse-hidden
          %li.dropdown
            %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
              Sign In
              %span.glyphicon.glyphicon-chevron-down
            .dropdown-menu{style: "padding: 15px"}
              = form_for User.new, url: session_path(:user), html: {class: "", role: "Sign-In"} do |f|
                .form-group
                  = f.label :username, class: "sr-only"
                  = f.text_field :username, class: "form-control", placeholder: "RIT Username"
                .form-group
                  = f.label :password, class: "sr-only"
                  = f.password_field :password, class: "form-control", placeholder: "Password"
                .form-group
                  = f.label :remember_me, class: "checkbox" do
                    = f.check_box :remember_me
                    Remember Me
                .form-group
                  = f.submit "Login", class: "btn btn-primary", style: "width: 100%"
        -# IF THE NAVBAR IS NOT COLLAPSED
        %ul.nav.navbar-nav.navbar-collapse-only
          %li= link_to "Sign In", session_path(:user)

app/views/shared/_username.html.haml
-# Render a user's name (with a mod or admin tag if appropriate)
-# To use, call render 'shared/username', user: user
- if user
  = link_to user.name, user_path(user)
  - if user.admin?
    %span.label.label-primary Admin
  - elsif user.mod?
    %span.label.label-primary Mod
- else
  = "Anonymous User"