config/routes.rb
TigerLaundry::Application.routes.draw do

  devise_for :users

  resources :facilities do
    resources :submissions do
      collection do
        get 'limited'
      end
    end
  end

  resources :users


  # Map the root of the site to the pages controller
  root to: "pages#index"
  get 'about', to: "pages#about"
  
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  has_many :submissions, dependent: :destroy

  # returns the most recent submission
  def last_submission
    submissions.last
  end

  # Get the status of the washers
  # returns either :full, :almost_full, or :open
  def washers_status
    get_status last_submission.washers
  end

  # Get the status of the driers
  # returns either :full, :almost_full, or :open
  def driers_status
    get_status last_submission.driers
  end

  # Gets the most severe status of washers and driers
  # from least to greatest in order of severity:
  #      :unknown, :open, :almost_full, :full
  def status
    if not last_submission
      return :unknown
    end
    
    w_s = washers_status
    d_s = driers_status
    
    if w_s == :full or d_s == :full
      return :full
    elsif w_s == :almost_full or d_s == :almost_full
      return :almost_full
    end
    return :open
  end


  private
  
  # get the status of the given number
  # returns either :full, :almost_full, or :open
  def get_status(n)
    if n >= 95
      return :full
    elsif n >= 75
      return :almost_full
    else
      return :open
    end
  end
  
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    authorize! :read, Facility
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    authorize! :read, @facility
  end

  # GET /facilities/new
  def new
    authorize! :create, Facility
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
    authorize! :update, @facility
  end

  # POST /facilities
  # POST /facilities.json
  def create
    authorize! :create, Facility
    @facility = Facility.new(facility_params)
    # make sure a facility has at least 1 submission

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility,
                                  notice: 'Facility was successfully created.' }
        format.json { render action: 'show',
                             status: :created, location: @facility }
      else
        format.html { render action: 'new' }
        format.json { render json: @facility.errors,
                                   status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    authorize! :update, @facility
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    authorize! :destroy, @facility
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:washers, :driers, :name)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.haml
= form_for @facility, html: {class: "form-horizontal"} do |f|
  - if @facility.errors.any?
    #error_explanation
      %h2= "#{pluralize(@facility.errors.count, "error")} prohibited this facility from being saved:"
      %ul
        - @facility.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: "control-label col-md-2"
    .col-md-10
      = f.text_field :name, class: "form-control", placeholder: "Name"
  .form-group
    = f.label :washers, class: "control-label col-md-2"
    .col-md-10
      = f.number_field :washers, class: "form-control", placeholder: "Washers"
  .form-group
    = f.label :driers, class: "control-label col-md-2"
    .col-md-10
      = f.number_field :driers, class: "form-control", placeholder: "Driers"
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit 'Save', class: "btn btn-primary"

app/views/facilities/edit.html.haml
%h1 Editing Facility

= render 'form'

.btn-group
  = link_to 'Show', @facility, class: "btn btn-default"
  = link_to 'Show All', facilities_path, class: "btn btn-default"

app/views/facilities/index.html.haml
%h1.text-center{style: "margin-bottom: 30px;"} All Facilities

.row
  .col-md-3
    -# List all of the facilities
    %ul.nav.nav-stacked.nav-pills.island
      - @facilities.each do |facility|
        %li= link_to facility.name, facility_path(facility)
      - if can? :create, Facility
        %li
          %a{href: new_facility_path}
            %span.glyphicon.glyphicon-plus
            New Facility
  .col-md-9
    - @facilities.each do |facility|
      .row
        .linksGraph.panel.panel-default.island
          .panel-body
            .links
              %h2{:style => "margin: 0px;"}
                = link_to facility_path(facility) do
                  %strong><
                    = facility.name.gsub(/\s+/, "")
                  Laundry
              %span{:style => "line-height: 40px;"}
                - if facility.submissions.last
                  Last updated
                  = time_ago_in_words(facility.submissions.last.created_at)
                  ago
                - else
                  No Recent Submissions
            .graph.facility-graph.draw-xaxis.draw-yaxis{:"facility-id" => facility.id, :data => {'height' => 150, 'margin' => 0}}

app/views/facilities/new.html.haml
%h1 New facility

= render 'form'

= link_to 'Back', facilities_path, class: "btn btn-default"

app/views/facilities/show.html.haml
%h1.text-center= @facility.name

.row
  .col-md-6
    .facility-graph.draw-xaxis.draw-yaxis.island{:"facility-id"=>@facility.id}
  .col-md-6
    .panel.panel-default.island
      .panel-body
        .row
          %b.col-md-4.text-right Name:
          .col-md-8= @facility.name
        = render "submissions/status_summary",
                 submission: @facility.last_submission
        .row
          .col-md-12
            .btn-group
              - if can? :create, Submission
                = link_to "New Submission",
                          new_facility_submission_path(@facility),
                          class: "btn btn-primary"
              - if can? :read, Submission
                = link_to "Show Submissions",
                          facility_submissions_path(@facility),
                          class: "btn btn-default"

.btn-group
  - if can? :update, @facility
    = link_to 'Edit', edit_facility_path(@facility), class: "btn btn-default"
  - if can? :destroy, @facility
    = link_to 'Destroy', facility_path(@facility),
      :method => :delete,
      :data => { :confirm => 'Are you sure?' },
      class: "btn btn-default"
  - if can? :read, Facility
    = link_to 'Show All', facilities_path, class: "btn btn-default"