config/routes.rb
TigerLaundry::Application.routes.draw do

  devise_for :users

  resources :facilities do
    resources :submissions do
      collection do
        get 'limited'
      end
    end
  end

  resources :users


  # Map the root of the site to the pages controller
  root to: "pages#index"
  get 'about', to: "pages#about"
  
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :facility
  belongs_to :user
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_facility
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET facilities/1/submissions
  # GET facilities/1/submissions.json
  def index
    authorize! :read, Submission
    @submissions = Facility.find(params[:facility_id]).submissions
  end

  # GET /facilities/1/submissions/1
  # GET /facilities/1/submissions/1.json
  def show
    authorize! :read, @submission
  end

  # GET /facilities/1/submissions/new
  def new
    authorize! :create, Submission
    @submission = Submission.new
  end

  # GET /facilities/1/submissions/1/edit
  def edit
    authorize! :update, @submission
  end

  # POST /facilities/1/submissions
  # POST /facilities/1/submissions.json
  def create
    @submission = Submission.new(submission_params)
    if user_signed_in?
      @submission.user = current_user
    end
    authorize! :create, @submission

    respond_to do |format|
      if @submission.save
        format.html { redirect_to facility_path(@facility), notice: 'Submission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @submission }
      else
        format.html { render action: 'new' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1/submissions/1
  # PATCH/PUT /facilities/1/submissions/1.json
  def update
    authorize! :update, @submission
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to facility_submission_path(@facility, @submission), notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1/submissions/1
  # DELETE /facilities/1/submissions/1.json
  def destroy
    authorize! :destroy, @submission
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to facility_submissions_url(@facility) }
      format.json { head :no_content }
    end
  end

  # GET /facilities/1/submissions/limited.json
  # Params expected:
  #   hours: integer - default 24, how many hours of submissions to get
  def limited
    authorize! :read, Submission
    if not params[:hours]
      hours = 12
    else
      hours = params[:hours].to_i
    end
    hours = hours.hours.ago
    @submissions = Submission.where("facility_id = ? AND created_at > ?",
                                    params[:facility_id], hours)
    if @submissions.empty?
      @submissions = [Submission.new(:facility_id => params[:facility_id], :washers => 0, :driers => 0, :created_at => Time.now)]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility   = Facility.find(params[:facility_id])
    end
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:washers, :driers, :facility_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.haml
= form_for [@facility, @submission], html: {class: "form-horizontal"} do |f|
  - if @submission.errors.any?
    #error_explanation
      %h2= "#{pluralize(@submission.errors.count, "error")} prohibited this submission from being saved:"
      %ul
        - @submission.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :facility_id, value: @facility.id
  .form-group
    = f.label :washers, class: "control-label col-md-2"
    .col-md-6
      = f.number_field :washers, class: "tl-slider tl-slider-machinestatus", :"value-holder" => "#washersSliderValHolder"
    .col-md-4
      -# value of the slider is inserted into this span
      %span#washersSliderValHolder.tl-slider-value> 0
      \% full
  .form-group
    = f.label :driers, class: "control-label col-md-2"
    .col-md-6
      = f.number_field :driers, class: "tl-slider tl-slider-machinestatus", :"value-holder" => "#driersSliderValHolder"
    .col-md-4
      -# value of the slider is inserted into this span
      %span#driersSliderValHolder.tl-slider-value> 0
      \% full
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit 'Save', class: "btn btn-primary"

app/views/submissions/_status_summary.html.haml
-# This abstracts making summaries of the last submissions
-# Params:
-#   submission    - the submission to summarize
-# Example:
-#   Washers in use: 25% of 10
-# Driers in use:  23% of 12
-#   Submitted by Foo
-#   3 hours ago

- if submission
  .row
    %b.col-md-4.text-right Washers in use:
    .col-md-8
      = submission.washers.to_s + "%"
      of
      = submission.facility.washers
  .row
    %b.col-md-4.text-right Driers in use:
    .col-md-8
      = submission.driers.to_s + '%'
      of
      = submission.facility.driers
  .row
    %b.col-md-4.text-right Reported By:
    .col-md-8
      = render 'shared/username', user: submission.user
  .row
    .col-md-8.col-md-offset-4
      %small{title: submission.created_at}
        = time_ago_in_words(submission.created_at)
        ago
- else
  .row
    .col-md-12
      No submission available

app/views/submissions/edit.html.haml
%h1 Editing Submission

= render 'form'

.btn-group
  = link_to 'Show', facility_submission_path(@facility, @submission), class: "btn btn-default"
  = link_to 'Show All', facility_submissions_path(@facility), class: "btn btn-default"

app/views/submissions/index.html.haml
%h1
  Listing Submissions for 
  = @facility.name

.table-responsive
  %table.table
    %tr
      %th Washers
      %th Driers
      %th Facility
      %th Operations

    - @submissions.each do |submission|
      %tr
        %td= submission.washers
        %td= submission.driers
        - if submission.facility
          %td= submission.facility.name
        - else
          %td No Facility
        %td
          .btn-group
            - if can? :read, submission
              = link_to 'Show', facility_submission_path(@facility, submission), class: "btn btn-default"
            - if can? :update, submission
              = link_to 'Edit', edit_facility_submission_path(@facility, submission), class: "btn btn-default"
            - if can? :destroy, submission
              = link_to 'Destroy', facility_submission_path(@facility, submission),
                  :method => :delete,
                  :data => { :confirm => 'Are you sure?' },
                  class: "btn btn-default"

%br

= link_to 'New Submission', new_facility_submission_path(@facility), class: "btn btn-primary"

app/views/submissions/new.html.haml
%h1 New submission

= render 'form'

= link_to 'Back', facility_path(@facility), class: "btn btn-default"

app/views/submissions/show.html.haml
%h1 
  Submission for 
  - if @submission.facility
    = @submission.facility.name
  - else
    = "No Facility"

.row
  %b.col-md-1.text-right Washers:
  %div.col-md-11= @submission.washers
.row
  %b.col-md-1.text-right Driers:
  %div.col-md-11= @submission.driers
.row
  %b.col-md-1.text-right Facility:
  - if @submission.facility
    %div.col-md-11= @submission.facility.name
  - else
    %div.col-md-11 No Facility

%br

.btn-group
  - if can? :update, @submission
    = link_to 'Edit', edit_facility_submission_path(@facility, @submission), class: "btn btn-default"
  - if can? :read, Submission
    = link_to 'Show All', facility_submissions_path(@facility), class: "btn btn-default"